=== getsentry/sentry-javascript/packages/e2e-tests/test-recipe-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Sentry JavaScript E2E Test Recipe",
  "type": "object",
  "properties": {
    "testApplicationName": {
      "type": "string",
      "description": "Name displayed in test output"
    },
    "buildCommand": {
      "type": "string",
      "description": "Command that is run to install dependencies and build the test application. This command is only run once before all tests. Working directory of the command is the root of the test application."
    },
    "buildAssertionCommand": {
      "type": "string",
      "description": "Command to verify build output. This command will be run after the build is complete. The command will receive the STDOUT of the `buildCommand` as STDIN."
    },
    "buildTimeoutSeconds": {
      "type": "number",
      "description": "Timeout for the build command in seconds. Default: 5 minutes"
    },
    "testTimeoutSeconds": {
      "type": "number",
      "description": "Timeout for the test command in seconds. Default: 2 minutes"
    },
    "tests": {
      "type": "array",
      "description": "Tests to run in this test application",
      "items": {
        "type": "object",
        "properties": {
          "testName": {
            "type": "string",
            "description": "Name displayed in test output"
          },
          "testCommand": {
            "type": "string",
            "description": "Command that is run to start the test. Working directory of the command is the root of the test application. If this command returns a non-zero exit code the test counts as failed."
          },
          "timeoutSeconds": {
            "type": "number",
            "description": "Test timeout in seconds. Default: 60"
          }
        },
        "required": ["testName", "testCommand"]
      }
    },
    "versions": {
      "type": "array",
      "description": "List of different dependency versions to test. If this property is provided, the tests will run for each item, if it is omitted, the tests will only run once with the dependencies provided in package.json.",
      "items": {
        "type": "object",
        "properties": {
          "dependencyOverrides": {
            "type": "object",
            "description": "Object to merge with the \"dependencies\" object in package.json.",
            "additionalProperties": { "type": "string" }
          }
        }
      }
    },
    "canaryVersions": {
      "type": "array",
      "description": "List of different dependency versions to test as part of the canary test. Canary tests are only run if the CANARY_E2E_TEST environment variable is set. If If CANARY_E2E_TEST is set and this property is provided, the tests will run for each item, if it is omitted, no tests will be executed.",
      "items": {
        "type": "object",
        "properties": {
          "dependencyOverrides": {
            "type": "object",
            "description": "Object to merge with the \"dependencies\" object in package.json.",
            "additionalProperties": { "type": "string" }
          }
        }
      }
    }
  },
  "required": ["testApplicationName", "tests"]
}

=== getsentry/sentry-javascript/packages/e2e-tests/test-applications/standard-frontend-react/test-recipe.json
{
  "$schema": "../../test-recipe-schema.json",
  "testApplicationName": "standard-frontend-react",
  "buildCommand": "pnpm install && npx playwright install && pnpm build",
  "tests": [
    {
      "testName": "Playwright tests",
      "testCommand": "yarn test"
    }
  ],
  "canaryVersions": [
    {
      "dependencyOverrides": {
        "react": "latest",
        "react-dom": "latest"
      }
    }
  ]
}

=== getsentry/sentry-javascript/packages/e2e-tests/test-applications/nextjs-app-dir/test-recipe.json
{
  "$schema": "../../test-recipe-schema.json",
  "testApplicationName": "nextjs-13-app-dir",
  "buildCommand": "yarn install --mutex network && npx playwright install && yarn build",
  "buildAssertionCommand": "yarn ts-node --script-mode assert-build.ts",
  "tests": [
    {
      "testName": "Prod Mode",
      "testCommand": "yarn test:prod"
    },
    {
      "testName": "Dev Mode",
      "testCommand": "yarn test:dev"
    }
  ],
  "canaryVersions": [
    {
      "dependencyOverrides": {
        "next": "latest"
      }
    },
    {
      "dependencyOverrides": {
        "next": "canary"
      }
    }
  ]
}

=== getsentry/sentry-javascript/packages/e2e-tests/test-applications/standard-frontend-react-tracing-import/test-recipe.json
{
  "$schema": "../../test-recipe-schema.json",
  "testApplicationName": "standard-frontend-react-tracing-import",
  "buildCommand": "pnpm install && npx playwright install && pnpm build",
  "tests": [
    {
      "testName": "Playwright tests",
      "testCommand": "yarn test"
    }
  ],
  "canaryVersions": []
}
